name: office-revenues
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - python
  - matplotlib
  - seaborn
  - ipykernel
  - xlwings
  - openpyxl
  - django
  - streamlit
  - plotly
  - watchdog
  - mitoinstaller
  - mitosheet
